---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cgicloudnative/concourse-alpine
 
inputs:
- name: certbot-dns-repo
- name: cert-repo
- name: letsencrypt
outputs:
- name: cert-repo-modified

params:
  EMAIL_ADDRESS:

run:
  path: certbot-dns-repo/pipeline/tasks/commit-cert-to-git.sh
