---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: certbot/dns-route53
 
inputs:
- name: certbot-dns-repo
- name: cert-repo
outputs:
- name: letsencrypt


params:
  LETSENCRYPT_API_ENDPOINT:
  AWS_ACCESS_KEY_ID:
  AWS_SECRET_ACCESS_KEY:
  EMAIL_ADDRESS:
  DOMAINS:

run:
  path: certbot-dns-repo/pipeline/tasks/generate_cert.sh
